<?php
// HOW TO ADD A VERSION :
// ======================
// Create a folder name with version and put the version file into it
// All will be done automatically
// the "version".txt file will be generated by this script the first time a version is called

//Error management
error_reporting( E_ERROR );
//action when error is catch
function handleError($errno, $errstr,$error_file,$error_line){sendError("$errstr - $error_file:$error_line\n");}
//send error
function sendError($msg)
{
echo "Error : an error occurred $msg";
$msg .= " for user HTTP_X_FORWARDED_FOR " . $_SERVER['HTTP_X_FORWARDED_FOR']. "\n";
$msg .= " for user REMOTE_ADDR " . $_SERVER['REMOTE_ADDR']. "\n";
mail('admin@frogg.fr','Error on FroggPT version.php',$msg,null,'info@frogg.fr');
}
//error handler
set_error_handler("handleError");

//display version list
function displayVersion($dir)
{
$content=scandir($dir);
if(!empty($content))
	{
	foreach($content as $file)
		{
		if ($file==='.' or $file==='..')continue;
		if (is_dir($file)){echo $file."\n";}
		}
	}
else{sendError(', no version found');exit;}
}

//display version files
function displayVersionFile($dir)
{
$fileName=$dir . ".txt";
if(!file_exists($fileName))
	{
	$vfile = fopen($fileName, "w");
	createVersionFile($dir,$vfile);	
	fclose($vfile);
	}
readfile($fileName);
}

//create file version
function createVersionFile($dir,$vfile)
{
$dir=rtrim($dir,'/');
if(is_dir($dir))$dh=opendir($dir);
else{sendError('while reading version '.$dir.' files');exit;}
while(($file=readdir($dh))!==false)
	 {
	 if($file!=='.' && $file!=='..')
		{
		$path=$dir.'/'.$file;
		if(is_dir($path)){displayVersionFile($path,$vfile);}else{fwrite($vfile,$path."\n");}
		}
	 }
closedir($dh);	
}

//start script
if(isset($_GET['version']) && $_GET['version']!='')
	{displayVersionFile($_GET['version']);}
else{displayVersion('./');}
?>